<?php

interface SourPHPUrlCacheInterface {


    /**
     * generate url hash to store
     * 
     * @param string $url
     * @return string hashedUrl
     */
    function hashUrl($url, $prefix=null);


    /**
     * detects if cache expired or not
     * 
     * @param string $hash url hash generated by hashUrl()
     * @param int $cacheLifetime
     * @return bool 
     */
    function isExpired($hashed, $cacheLifetime);


    /**
     * regenerates data to key $hashedUrl
     *
     * @param string $hashedUrl 
     * @param string $data fetched url data
     * @return string generated data
     */
    function regenerateData($hashedUrl, $data);


    /**
     * returns data from $hashedUrl
     *
     * @param string $hashedUrl
     * @return string current data
     */
    function getCurrentData($hashedUrl);

}
